id: A1A814BF3
title: 'The Single Mudrā: A Daily Practice for the Awesome Ones’ Assembly (Palchen
  Düpa), the Heart Practice of the Awareness-Holders'
type: translation
pechas:
- I4E48264D
- IE6CFA536
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:37:31.484568
  last_modified_at: 2023-01-04 12:37:31.484570
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  I4E48264D/6E0A: 555B
  IE6CFA536/CFE8: 555B
